# Note:
# 1. This file does not automatically reloaded even when `--livereload`.
# 2. Jekyll has data files feature for frequently updated data



# Site settings
# These values can be accessed like {{ site.email }} in HTML or Markdown files.
title: 合同会社inctore
email:
locale: ja-JP
description: >-
  Homepage of inctore llc.. A company of freelance programmer / data scientist Y. Horikoshi.
twitter_username: hotoku
github_username: hotoku
minimal_mistakes_skin: "air" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
url: "https://www.inctore.com"
logo: /assets/images/logo.png
encoding: utf-8

masthead_title: " "

# Build settings
markdown: kramdown
# remote_theme: mmistakes/minimal-mistakes@4.24.0

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _plsit/
  - _plist2/
  - js/
  - docs/
  - test/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Yasunori Horikoshi"
  avatar : "/assets/images/bio-photo.png"
  bio    : "データサイエンティスト・データエンジニア・プログラマー。Python/R/C++/TypeScript。"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/hotoku"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hotoku"
    - label: "Qiita"
      icon: "fa-fw fa-solid fa-pen-nib"
      url: "https://qiita.com/hotoku"
    - label: "midium"
      icon: "fa-fw fa-solid fa-pen-nib"
      url: "https://medium.com/@hotoku"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/hotoku"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hotoku"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


